
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Mozu.Api.Contracts.Tenant
{
		///
		///	Properties of the domain that the tenant is associated with such as the domain name, the zone string, audit information (system-supplied and read-only), assignment data, and whether or not the domain is primary or requires a SSL for authentication.
		///
		public class Domain
		{
			public string CName { get; set; }

			///
			///Date and time when the entity was created, represented in UTC Date/Time.
			///
			public DateTime CreateDate { get; set; }

			///
			///The domain name of the tenant.
			///
			public string DomainName { get; set; }

			///
			///The IP address of the tenant domain.
			///
			public string IPAddress { get; set; }

			///
			///If true, this marker indicates that the entity is the primary entity in a set.
			///
			public bool IsPrimary { get; set; }

			///
			///If true, the entity is assigned by the system.
			///
			public bool IsSystemAssigned { get; set; }

			///
			///If true, this domain requires a secure transport security layer (secure socket layer (SSL)) to encrypt the information contained on the site. The SSL is usually used for authentication.
			///
			public bool RequiresSSL { get; set; }

			public int SiteId { get; set; }

			public int TenantId { get; set; }

			///
			///Date and time when the entity was last updated, represented in UTC Date/Time.
			///
			public DateTime UpdateDate { get; set; }

			///
			///The zone string for the tenant domain.
			///
			public string Zone { get; set; }

		}

}