
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mozu.Api.Contracts.CommerceRuntime.Discounts
{
		public class Discount
		{
			public DateTime? ExpirationDate { get; set; }

			public int Id { get; set; }

			public List<string> ItemIds { get; set; }

			public string Name { get; set; }

		}

}