
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mozu.Api.Clients.Platform.User
{
	/// <summary>
	/// Manage the user authentication tickets used to perform operations in the Mozu API.
	/// </summary>
	public partial class UserAuthTicketClient 	{
		
				/// <summary>
		/// Generates an authentication ticket for a user.
		/// </summary>
		/// <param name="userAuthInfo">The user authentication information, which consists of email address and password.</param>
		/// <returns>
		///  <see cref="Mozu.Api.MozuClient" />{<see cref="Mozu.Api.Contracts.Core.UserAuthTicket"/>}
		/// </returns>
		/// <example>
		/// <code>
		///   var mozuClient=CreateUserAuthTicket( userAuthInfo);
		///   var userAuthTicketClient = mozuClient.WithBaseAddress(url).Execute().Result();
		/// </code>
		/// </example>
		public static MozuClient<Mozu.Api.Contracts.Core.UserAuthTicket> CreateUserAuthTicketClient(Mozu.Api.Contracts.Core.UserAuthInfo userAuthInfo)
		{
			var url = Mozu.Api.Urls.Platform.User.UserAuthTicketUrl.CreateUserAuthTicketUrl();
			const string verb = "POST";
			var mozuClient = new MozuClient<Mozu.Api.Contracts.Core.UserAuthTicket>().WithVerb(verb).WithResourceUrl(url).WithBody<Mozu.Api.Contracts.Core.UserAuthInfo>(userAuthInfo);
		return mozuClient;

		}

		/// <summary>
		/// Generates an authentication ticket for a user that can be used for an individual site.
		/// </summary>
		/// <param name="userAuthInfo">The user authentication information, which consists of email address and password.</param>
		/// <returns>
		///  <see cref="Mozu.Api.MozuClient" />{<see cref="Mozu.Api.Contracts.Core.UserAuthTicket"/>}
		/// </returns>
		/// <example>
		/// <code>
		///   var mozuClient=CreateAuthTicketForSite( userAuthInfo);
		///   var userAuthTicketClient = mozuClient.WithBaseAddress(url).Execute().Result();
		/// </code>
		/// </example>
		public static MozuClient<Mozu.Api.Contracts.Core.UserAuthTicket> CreateAuthTicketForSiteClient(Mozu.Api.Contracts.Core.UserTokenInfo userAuthInfo)
		{
			var url = Mozu.Api.Urls.Platform.User.UserAuthTicketUrl.CreateAuthTicketForSiteUrl();
			const string verb = "POST";
			var mozuClient = new MozuClient<Mozu.Api.Contracts.Core.UserAuthTicket>().WithVerb(verb).WithResourceUrl(url).WithBody<Mozu.Api.Contracts.Core.UserTokenInfo>(userAuthInfo);
		return mozuClient;

		}

				/// <summary>
		/// Refresh the user authentication ticket by supplying the refresh token.
		/// </summary>
		/// <param name="refreshToken">The refresh token generated in the user authentication ticket.</param>
		/// <returns>
		///  <see cref="Mozu.Api.MozuClient" />{<see cref="Mozu.Api.Contracts.Core.UserAuthTicket"/>}
		/// </returns>
		/// <example>
		/// <code>
		///   var mozuClient=RefreshUserAuthTicket( refreshToken);
		///   var userAuthTicketClient = mozuClient.WithBaseAddress(url).Execute().Result();
		/// </code>
		/// </example>
		public static MozuClient<Mozu.Api.Contracts.Core.UserAuthTicket> RefreshUserAuthTicketClient(string refreshToken)
		{
			var url = Mozu.Api.Urls.Platform.User.UserAuthTicketUrl.RefreshUserAuthTicketUrl(refreshToken);
			const string verb = "PUT";
			var mozuClient = new MozuClient<Mozu.Api.Contracts.Core.UserAuthTicket>().WithVerb(verb).WithResourceUrl(url);
		return mozuClient;

		}

				
	}

}


