
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mozu.Api.Contracts.Content
{
		public class DocumentType
		{
			public string Description { get; set; }

			public string DisplayName { get; set; }

			public string DocumentTypeScope { get; set; }

			public string Name { get; set; }

			public string ParentTypeName { get; set; }

			public List<LocalizedString> LocalizedDescriptions { get; set; }

			public List<LocalizedString> LocalizedDisplayNames { get; set; }

			public List<PropertyType> PropertyTypes { get; set; }

		}

}