
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mozu.Api.Contracts.Content
{
		///
		///	The hierarchical structure of the folders in a document list including root folder, parent folder, and subfolders.
		///
		public class FolderTree
		{
			///
			///The name of the folder.
			///
			public Folder Folder { get; set; }

			///
			///The subfolders contained within a folder.
			///
			public List<FolderTree> Children { get; set; }

		}

}