
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Mozu.Api.Urls.Content.Documentlists
{
	public partial class DocumentUrl : BaseUrl
	{

		/// <summary>
        /// Get Resource Url for GetDocumentContent
        /// </summary>
        /// <param name="documentId">Unique identifier of the document.</param>
        /// <param name="documentListName">The name of the document list associated with the document.</param>
        /// <param name="publishState">The current state of the document, which is Active, Draft, or Latest. Active documents are published and cannot be deleted. Querying Latest returns the most recent version of the document, regardless of whether it is published or a draft.</param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static string GetDocumentContentUrl(string documentId, string documentListName, string publishState)
		{
			var url = "/api/content/documentlists/{documentListName}/documents/{documentId}/content?publishState={publishState}";
			FormatUrl( ref url, "documentId", documentId);
			FormatUrl( ref url, "documentListName", documentListName);
			FormatUrl( ref url, "publishState", publishState);
			return url;
		}

		/// <summary>
        /// Get Resource Url for GetDocument
        /// </summary>
        /// <param name="documentId">Identifier of the document being retrieved.</param>
        /// <param name="documentListName">The name of the document list associated with the document to retrieve.</param>
        /// <param name="publishState">The current state of the document, which is Active, Draft, or Latest. Active documents are published and cannot be deleted. Querying Latest returns the most recent version of the document, regardless of whether it is published or a draft.</param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static string GetDocumentUrl(string documentId, string documentListName, string publishState)
		{
			var url = "/api/content/documentlists/{documentListName}/documents/{documentId}?publishState={publishState}";
			FormatUrl( ref url, "documentId", documentId);
			FormatUrl( ref url, "documentListName", documentListName);
			FormatUrl( ref url, "publishState", publishState);
			return url;
		}

		/// <summary>
        /// Get Resource Url for GetDocuments
        /// </summary>
        /// <param name="documentListName">The name of the document list.</param>
        /// <param name="filter">A set of expressions that consist of a field, operator, and value and represent search parameter syntax when filtering results of a query. You can filter a document's search results by any of its properties, including its name or folder path. Valid operators include equals (eq), does not equal (ne), greater than (gt), less than (lt), greater than or equal to (ge), less than or equal to (le), starts with (sw), or contains (cont). <b>For example - "filter=Name+sw+Events"</b></param>
        /// <param name="pageSize">Specifies the number of results to display on each page when creating paged results from a query. The maximum value is 200.</param>
        /// <param name="publishState">The current state of the document, which is Active, Draft, or Latest. Active documents are published and cannot be deleted. Querying Latest returns the most recent version of the document, regardless of whether it is published or a draft.</param>
        /// <param name="sortBy">The property by which to sort results and whether the results appear in ascending (a-z) order, represented by ASC or in descending (z-a) order, represented by DESC. The sortBy parameter follows an available property. For example: "sortBy=productCode+asc"</param>
        /// <param name="startIndex">Indicates the zero-based offset in the complete result set where the returned entities begin, when creating paged results from a query. For example, with a PageSize of 25, to get the 51st through the 75th items, use startIndex=3.</param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static string GetDocumentsUrl(string documentListName, string filter, long? pageSize, string publishState, string sortBy, long? startIndex)
		{
			var url = "/api/content/documentlists/{documentListName}/documents?publishState={publishState}&filter={filter}&sortBy={sortBy}&pageSize={pageSize}&startIndex={startIndex}";
			FormatUrl( ref url, "documentListName", documentListName);
			FormatUrl( ref url, "filter", filter);
			FormatUrl( ref url, "pageSize", pageSize);
			FormatUrl( ref url, "publishState", publishState);
			FormatUrl( ref url, "sortBy", sortBy);
			FormatUrl( ref url, "startIndex", startIndex);
			return url;
		}

				/// <summary>
        /// Get Resource Url for CreateDocument
        /// </summary>
        /// <param name="documentListName">The descriptive alphanumeric document list name being created.</param>
        /// <param name="publishState">The current state of the document, which is Active, Draft, or Latest. Active documents are published and cannot be deleted. Querying Latest returns the most recent version of the document, regardless of whether it is published or a draft.</param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static string CreateDocumentUrl(string documentListName, string publishState)
		{
			var url = "/api/content/documentlists/{documentListName}/documents?publishState={publishState}";
			FormatUrl( ref url, "documentListName", documentListName);
			FormatUrl( ref url, "publishState", publishState);
			return url;
		}

				/// <summary>
        /// Get Resource Url for UpdateDocumentContent
        /// </summary>
        /// <param name="documentId">Unique identifier of the document.</param>
        /// <param name="documentListName">The name of the document list associated with the document.</param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static string UpdateDocumentContentUrl(string documentId, string documentListName)
		{
			var url = "/api/content/documentlists/{documentListName}/documents/{documentId}/content";
			FormatUrl( ref url, "documentId", documentId);
			FormatUrl( ref url, "documentListName", documentListName);
			return url;
		}

		/// <summary>
        /// Get Resource Url for UpdateDocument
        /// </summary>
        /// <param name="documentId">Unique identifier of the document to update.</param>
        /// <param name="documentListName">Name of the document list associated with the document.</param>
        /// <param name="publishState">The current state of the document, which is Active, Draft, or Latest. Active documents are published and cannot be deleted. Querying Latest returns the most recent version of the document, regardless of whether it is published or a draft.</param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static string UpdateDocumentUrl(string documentId, string documentListName, string publishState)
		{
			var url = "/api/content/documentlists/{documentListName}/documents/{documentId}?publishState={publishState}";
			FormatUrl( ref url, "documentId", documentId);
			FormatUrl( ref url, "documentListName", documentListName);
			FormatUrl( ref url, "publishState", publishState);
			return url;
		}

				/// <summary>
        /// Get Resource Url for DeleteDocumentContent
        /// </summary>
        /// <param name="documentId">Unique identifier of the document.</param>
        /// <param name="documentListName">The name of the document list associated with the document.</param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static string DeleteDocumentContentUrl(string documentId, string documentListName)
		{
			var url = "/api/content/documentlists/{documentListName}/documents/{documentId}/content";
			FormatUrl( ref url, "documentId", documentId);
			FormatUrl( ref url, "documentListName", documentListName);
			return url;
		}

		/// <summary>
        /// Get Resource Url for DeleteDocument
        /// </summary>
        /// <param name="documentId">Identifier of the document being deleted.</param>
        /// <param name="documentListName">The name of the document list associated with the document list being deleted.</param>
        /// <param name="publishState">The current state of the document, which is Active, Draft, or Latest. Active documents are published and cannot be deleted. Querying Latest returns the most recent version of the document, regardless of whether it is published or a draft.</param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static string DeleteDocumentUrl(string documentId, string documentListName, string publishState)
		{
			var url = "/api/content/documentlists/{documentListName}/documents/{documentId}?publishState={publishState}";
			FormatUrl( ref url, "documentId", documentId);
			FormatUrl( ref url, "documentListName", documentListName);
			FormatUrl( ref url, "publishState", publishState);
			return url;
		}

		
	}
}

