
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mozu.Api.Resources.Platform.User
{
	/// <summary>
	/// Use this resource to manage shopper accounts for your Mozu tenant.
	/// </summary>
	public partial class UserResource : BaseResource 	{
				///
		/// <see cref="Mozu.Api.ApiContext"/>
		///
		private readonly ApiContext _apiContext;
		public UserResource(ApiContext apiContext) 
		{
			_apiContext = apiContext;
		}

		
		/// <summary>
		/// Retrieves the details of a user account by supplying the user's email address.
		/// </summary>
		/// <param name="emailAddress">The email address of the specified user or the email address associated with the specified entity.</param>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.Core.User"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var user = new User();
		///   var user = user.GetUserByEmail( emailAddress);
		/// </code>
		/// </example>
		public virtual Mozu.Api.Contracts.Core.User GetUserByEmail(string emailAddress)
		{
						MozuClient<Mozu.Api.Contracts.Core.User> response;
			var client = Mozu.Api.Clients.Platform.User.UserClient.GetUserByEmailClient( emailAddress);
			SetContext(_apiContext, ref client,true);
			response= client.Execute();
			return response.Result();

		}

		/// <summary>
		/// Retrieves the details of a user account by supplying the user ID.
		/// </summary>
		/// <param name="userId">Unique identifier of the user.</param>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.Core.User"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var user = new User();
		///   var user = user.GetUser( userId);
		/// </code>
		/// </example>
		public virtual Mozu.Api.Contracts.Core.User GetUser(string userId)
		{
						MozuClient<Mozu.Api.Contracts.Core.User> response;
			var client = Mozu.Api.Clients.Platform.User.UserClient.GetUserClient( userId);
			SetContext(_apiContext, ref client,true);
			response= client.Execute();
			return response.Result();

		}

				/// <summary>
		/// Creates a new shopper user account.
		/// </summary>
		/// <param name="shopper">Properties of the new shopper user account to create.</param>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.Core.User"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var user = new User();
		///   var user = user.CreateUser( shopper);
		/// </code>
		/// </example>
		public virtual Mozu.Api.Contracts.Core.User CreateUser(Mozu.Api.Contracts.Core.User shopper)
		{
						MozuClient<Mozu.Api.Contracts.Core.User> response;
			var client = Mozu.Api.Clients.Platform.User.UserClient.CreateUserClient( shopper);
			SetContext(_apiContext, ref client,true);
			response= client.Execute();
			return response.Result();

		}

		/// <summary>
		/// Creates a bulk collection of new shopper user accounts.
		/// </summary>
		/// <param name="users">Properties of the new shopper user accounts to create.</param>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.Core.UserCollection"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var user = new User();
		///   var userCollection = user.CreateUsers( users);
		/// </code>
		/// </example>
		public virtual Mozu.Api.Contracts.Core.UserCollection CreateUsers(Mozu.Api.Contracts.Core.UserCollection users)
		{
						MozuClient<Mozu.Api.Contracts.Core.UserCollection> response;
			var client = Mozu.Api.Clients.Platform.User.UserClient.CreateUsersClient( users);
			SetContext(_apiContext, ref client,true);
			response= client.Execute();
			return response.Result();

		}

		/// <summary>
		/// Logs a shopper user in to a tenant.
		/// </summary>
		/// <param name="userAuthInfo">The authentication information required to log the user in, which consists of email address and password.</param>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.User.UserLoginResult"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var user = new User();
		///   var userLoginResult = user.Login( userAuthInfo);
		/// </code>
		/// </example>
		public virtual Mozu.Api.Contracts.User.UserLoginResult Login(Mozu.Api.Contracts.Core.UserAuthInfo userAuthInfo)
		{
						MozuClient<Mozu.Api.Contracts.User.UserLoginResult> response;
			var client = Mozu.Api.Clients.Platform.User.UserClient.LoginClient( userAuthInfo);
			SetContext(_apiContext, ref client,true);
			response= client.Execute();
			return response.Result();

		}

		/// <summary>
		/// Reset the shopper user password by supplying the email address.
		/// </summary>
		/// <param name="resetPasswordInfo">The information required to reset the password, which consists of the user email address.</param>
		/// <returns>
		/// 
		/// </returns>
		/// <example>
		/// <code>
		///   var user = new User();
		///   user.ResetPassword( resetPasswordInfo);
		/// </code>
		/// </example>
		public virtual void ResetPassword(Mozu.Api.Contracts.User.ResetPasswordInfo resetPasswordInfo)
		{
						MozuClient response;
			var client = Mozu.Api.Clients.Platform.User.UserClient.ResetPasswordClient( resetPasswordInfo);
			SetContext(_apiContext, ref client,true);
			response= client.Execute();

		}

						
	}

}


