
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Mozu.Api.Contracts.Core
{
		///
		///	Properties of a piece of functionality in the Mozu system.
		///
		public class Feature
		{
			///
			///Identifier of the entity.
			///
			public int Id { get; set; }

			///
			///The name of the feature.
			///
			public string Name { get; set; }

			///
			///Version associated with this feature.
			///
			public string Version { get; set; }

		}

}