
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mozu.Api.Contracts.Core
{
		public class User
		{
			public string EmailAddress { get; set; }

			public string FirstName { get; set; }

			public string Id { get; set; }

			public bool IsActive { get; set; }

			public string LastName { get; set; }

			public string LocaleCode { get; set; }

			public string Password { get; set; }

			public List<UserRole> Roles { get; set; }

			public UserSystemData SystemData { get; set; }

		}

}