
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mozu.Api.Resources.Commerce.Settings
{
	/// <summary>
	/// Use the applications subresource to update site settings for installed applications.
	/// </summary>
	public partial class ApplicationResource : BaseResource 	{
				///
		/// <see cref="Mozu.Api.ApiContext"/>
		///
		private readonly ApiContext _apiContext;
		public ApplicationResource(ApiContext apiContext) 
		{
			_apiContext = apiContext;
		}

		
						/// <summary>
		/// Initializes an application with the necessary configured settings.
		/// </summary>
		/// <param name="application">Properties of the application to update.</param>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.SiteSettings.Application.Application"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var application = new Application();
		///   var application = application.ThirdPartyUpdateApplication( application);
		/// </code>
		/// </example>
		public virtual Mozu.Api.Contracts.SiteSettings.Application.Application ThirdPartyUpdateApplication(Mozu.Api.Contracts.SiteSettings.Application.Application application)
		{
						MozuClient<Mozu.Api.Contracts.SiteSettings.Application.Application> response;
			var client = Mozu.Api.Clients.Commerce.Settings.ApplicationClient.ThirdPartyUpdateApplicationClient( application);
			SetContext(_apiContext, ref client,true);
			response= client.Execute();
			return response.Result();

		}

				
	}

}


