
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Mozu.Api.Urls.Commerce
{
	public partial class ReturnUrl : MozuUrl
	{

		/// <summary>
        /// Get Resource Url for GetReturns
        /// </summary>
        /// <param name="filter"></param>
        /// <param name="pageSize"></param>
        /// <param name="sortBy"></param>
        /// <param name="startIndex"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetReturnsUrl(string filter, int? pageSize, string sortBy, int? startIndex)
		{
			var url = "/api/commerce/returns/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}";
			FormatUrl( ref url, "filter", filter);
			FormatUrl( ref url, "pageSize", pageSize);
			FormatUrl( ref url, "sortBy", sortBy);
			FormatUrl( ref url, "startIndex", startIndex);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

		/// <summary>
        /// Get Resource Url for GetReturn
        /// </summary>
        /// <param name="returnId"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetReturnUrl(string returnId)
		{
			var url = "/api/commerce/returns/{returnId}";
			FormatUrl( ref url, "returnId", returnId);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

		/// <summary>
        /// Get Resource Url for GetAvailableReturnActions
        /// </summary>
        /// <param name="returnId"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetAvailableReturnActionsUrl(string returnId)
		{
			var url = "/api/commerce/returns/{returnId}/actions";
			FormatUrl( ref url, "returnId", returnId);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

		/// <summary>
        /// Get Resource Url for GetPayments
        /// </summary>
        /// <param name="returnId"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetPaymentsUrl(string returnId)
		{
			var url = "/api/commerce/returns/{returnId}/payments";
			FormatUrl( ref url, "returnId", returnId);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

		/// <summary>
        /// Get Resource Url for GetPayment
        /// </summary>
        /// <param name="paymentId"></param>
        /// <param name="returnId"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetPaymentUrl(string paymentId, string returnId)
		{
			var url = "/api/commerce/returns/{returnId}/payments/{paymentId}";
			FormatUrl( ref url, "paymentId", paymentId);
			FormatUrl( ref url, "returnId", returnId);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

		/// <summary>
        /// Get Resource Url for GetAvailablePaymentActionsForReturn
        /// </summary>
        /// <param name="paymentId"></param>
        /// <param name="returnId"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetAvailablePaymentActionsForReturnUrl(string paymentId, string returnId)
		{
			var url = "/api/commerce/returns/{returnId}/payments/{paymentId}/actions";
			FormatUrl( ref url, "paymentId", paymentId);
			FormatUrl( ref url, "returnId", returnId);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

				/// <summary>
        /// Get Resource Url for CreateReturn
        /// </summary>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl CreateReturnUrl()
		{
			var url = "/api/commerce/returns/";
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

		/// <summary>
        /// Get Resource Url for PerformPaymentActionForReturn
        /// </summary>
        /// <param name="paymentId"></param>
        /// <param name="returnId"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl PerformPaymentActionForReturnUrl(string paymentId, string returnId)
		{
			var url = "/api/commerce/returns/{returnId}/payments/{paymentId}/actions";
			FormatUrl( ref url, "paymentId", paymentId);
			FormatUrl( ref url, "returnId", returnId);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

		/// <summary>
        /// Get Resource Url for CreatePaymentActionForReturn
        /// </summary>
        /// <param name="returnId"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl CreatePaymentActionForReturnUrl(string returnId)
		{
			var url = "/api/commerce/returns/{returnId}/payments/actions";
			FormatUrl( ref url, "returnId", returnId);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

		/// <summary>
        /// Get Resource Url for PerformReturnActions
        /// </summary>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl PerformReturnActionsUrl()
		{
			var url = "/api/commerce/returns/actions";
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

				/// <summary>
        /// Get Resource Url for UpdateReturn
        /// </summary>
        /// <param name="returnId"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl UpdateReturnUrl(string returnId)
		{
			var url = "/api/commerce/returns/{returnId}";
			FormatUrl( ref url, "returnId", returnId);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

				/// <summary>
        /// Get Resource Url for DeleteReturn
        /// </summary>
        /// <param name="returnId"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl DeleteReturnUrl(string returnId)
		{
			var url = "/api/commerce/returns/{returnId}";
			FormatUrl( ref url, "returnId", returnId);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

		
	}
}

