
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mozu.Api.Contracts.CommerceRuntime.Returns
{
		public class ReturnAction
		{
			public string ActionName { get; set; }

			public List<string> ReturnIds { get; set; }

		}

}