
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mozu.Api.Contracts.ShippingRuntime
{
		public class CustomAttribute
		{
			public string Key { get; set; }

			public string Value { get; set; }

			public List<CustomAttribute> ChildAttributes { get; set; }

		}

}