
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Mozu.Api.Urls.Content
{
	public partial class PropertyTypeUrl : MozuUrl
	{

		/// <summary>
        /// Get Resource Url for GetList
        /// </summary>
        /// <param name="pageSize">Used to create paged results from a query. Specifies the number of results to display on each page. Maximum: 200.</param>
        /// <param name="startIndex"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetListUrl(int? pageSize, int? startIndex)
		{
			var url = "/api/content/propertytypes/?pageSize={pageSize}&startIndex={startIndex}";
			FormatUrl( ref url, "pageSize", pageSize);
			FormatUrl( ref url, "startIndex", startIndex);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

		/// <summary>
        /// Get Resource Url for Get
        /// </summary>
        /// <param name="propertyTypeName">The name of the content property type.</param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetUrl(string propertyTypeName)
		{
			var url = "/api/content/propertytypes/{propertyTypeName}";
			FormatUrl( ref url, "propertyTypeName", propertyTypeName);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

		/// <summary>
        /// Get Resource Url for PropertyValueTypes
        /// </summary>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl PropertyValueTypesUrl()
		{
			var url = "/api/content/propertytypes/propertyvaluetypes";
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

								
	}
}

