
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Mozu.Api.Urls.Commerce.Catalog.Admin.Products
{
	public partial class ProductVariationUrl : MozuUrl
	{

		/// <summary>
        /// Get Resource Url for GetProductVariation
        /// </summary>
        /// <param name="productCode"></param>
        /// <param name="variationKey"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetProductVariationUrl(string productCode, string variationKey)
		{
			var url = "/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}";
			FormatUrl( ref url, "productCode", productCode);
			FormatUrl( ref url, "variationKey", variationKey);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

		/// <summary>
        /// Get Resource Url for GetProductVariations
        /// </summary>
        /// <param name="filter"></param>
        /// <param name="pageSize"></param>
        /// <param name="productCode"></param>
        /// <param name="sortBy"></param>
        /// <param name="startIndex"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetProductVariationsUrl(string filter, int? pageSize, string productCode, string sortBy, int? startIndex)
		{
			var url = "/api/commerce/catalog/admin/products/{productCode}/variations?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}";
			FormatUrl( ref url, "filter", filter);
			FormatUrl( ref url, "pageSize", pageSize);
			FormatUrl( ref url, "productCode", productCode);
			FormatUrl( ref url, "sortBy", sortBy);
			FormatUrl( ref url, "startIndex", startIndex);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

						/// <summary>
        /// Get Resource Url for UpdateProductVariations
        /// </summary>
        /// <param name="productCode"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl UpdateProductVariationsUrl(string productCode)
		{
			var url = "/api/commerce/catalog/admin/products/{productCode}/variations";
			FormatUrl( ref url, "productCode", productCode);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

		/// <summary>
        /// Get Resource Url for UpdateProductVariation
        /// </summary>
        /// <param name="productCode"></param>
        /// <param name="variationKey"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl UpdateProductVariationUrl(string productCode, string variationKey)
		{
			var url = "/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}";
			FormatUrl( ref url, "productCode", productCode);
			FormatUrl( ref url, "variationKey", variationKey);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

				/// <summary>
        /// Get Resource Url for DeleteProductVariation
        /// </summary>
        /// <param name="productCode"></param>
        /// <param name="variationKey"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl DeleteProductVariationUrl(string productCode, string variationKey)
		{
			var url = "/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}";
			FormatUrl( ref url, "productCode", productCode);
			FormatUrl( ref url, "variationKey", variationKey);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

		
	}
}

