
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Mozu.Api.Contracts.Core;

namespace Mozu.Api.Contracts.Customer
{
		public class CustomerAccount
		{
			public bool AcceptsMarketing { get; set; }

			public string CompanyOrOrganization { get; set; }

			public string ExternalId { get; set; }

			public int Id { get; set; }

			public bool TaxExempt { get; set; }

			public string TaxId { get; set; }

			public string UserId { get; set; }

			public List<CustomerAttribute> Attributes { get; set; }

			public AuditInfo AuditInfo { get; set; }

			public CommerceSummary CommerceSummary { get; set; }

			public List<CustomerContact> Contacts { get; set; }

			public List<CustomerGroup> Groups { get; set; }

			public List<CustomerInStockNotificationSubscription> InStockNotificationSubscriptions { get; set; }

			public List<CustomerNote> Notes { get; set; }

		}

}