
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Mozu.Api.Urls.Commerce.Settings.Checkout
{
	public partial class CustomerCheckoutSettingsUrl : MozuUrl
	{

		/// <summary>
        /// Get Resource Url for GetCustomerCheckoutSettings
        /// </summary>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetCustomerCheckoutSettingsUrl()
		{
			var url = "/api/commerce/settings/checkout/customercheckoutsettings";
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

						/// <summary>
        /// Get Resource Url for UpdateCustomerCheckoutSettings
        /// </summary>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl UpdateCustomerCheckoutSettingsUrl()
		{
			var url = "/api/commerce/settings/checkout/customercheckoutsettings";
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

				
	}
}

