
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Mozu.Api.Contracts.Core;

namespace Mozu.Api.Contracts.Core.Extensible
{
		///
		///	The properties of the attribute to extend for either customers or orders.
		///
		public class Attribute
		{
			///
			///Name of this extensible attribute in Mozu Admin.
			///
			public string AdminName { get; set; }

			///
			///Merchant-defined code for an extensible attribute.
			///
			public string AttributeCode { get; set; }

			public string AttributeFQN { get; set; }

			///
			///The data type of the attribute. There are four valid data types: "Bool", "DateTime", "Number", "String"
			///
			public string DataType { get; set; }

			///
			///Unique identifier of the extensible attribute.
			///
			public int? Id { get; set; }

			///
			///There are six valid input types: "YesNo", "Date", "DateTime", "List", "TextBox", "TextArea"
			///
			public string InputType { get; set; }

			///
			///If true, the customer or order attribute is active.
			///
			public bool? IsActive { get; set; }

			///
			///Namespace associated with this extensible attribute.
			///
			public string Namespace { get; set; }

			///
			///List of metadata defined for an extensible attribute.
			///
			public List<AttributeMetadataItem> AttributeMetadata { get; set; }

			public AuditInfo AuditInfo { get; set; }

			///
			///List of localized content properties for the extensible attribute.
			///
			public AttributeLocalizedContent Content { get; set; }

			///
			///Properties used when validating a value entered for an extensible attribute.
			///
			public AttributeValidation Validation { get; set; }

			///
			///List of valid vocabulary values defined for an attribute.
			///
			public List<AttributeVocabularyValue> VocabularyValues { get; set; }

		}

}