
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Mozu.Api.Urls.Platform.Adminuser
{
	public partial class TenantAdminUserAuthTicketUrl : BaseUrl
	{

				/// <summary>
        /// Get Resource Url for CreateUserAuthTicket
        /// </summary>
        /// <param name="tenantId">Unique identifier of the Mozu tenant or development store for which to generate the user authentication ticket.</param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static string CreateUserAuthTicketUrl(int? tenantId)
		{
			var url = "/api/platform/adminuser/authtickets/?tenantId={tenantId}";
			FormatUrl( ref url, "tenantId", tenantId);
			return url;
		}

				/// <summary>
        /// Get Resource Url for RefreshAuthTicket
        /// </summary>
        /// <param name="tenantId">Unique identifier of the Mozu tenant or development store for which to refresh the authentication ticket.</param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static string RefreshAuthTicketUrl(int? tenantId)
		{
			var url = "/api/platform/adminuser/authtickets/?tenantId={tenantId}";
			FormatUrl( ref url, "tenantId", tenantId);
			return url;
		}

				/// <summary>
        /// Get Resource Url for DeleteUserAuthTicket
        /// </summary>
        /// <param name="refreshToken">Refresh token string associated with the user authentication ticket.</param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static string DeleteUserAuthTicketUrl(string refreshToken)
		{
			var url = "/api/platform/adminuser/authtickets/?refreshToken={refreshToken}";
			FormatUrl( ref url, "refreshToken", refreshToken);
			return url;
		}

		
	}
}

