
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Mozu.Api.Security;


namespace Mozu.Api.Resources.Commerce
{
	/// <summary>
	/// 
	/// </summary>
	public partial class InStockNotificationSubscriptionResource  	{
		///
		/// <see cref="Mozu.Api.ApiContext"/>
		///
		private readonly IApiContext _apiContext;
		public InStockNotificationSubscriptionResource(IApiContext apiContext) 
		{
			_apiContext = apiContext;
		}

		
		/// <summary>
		/// 
		/// </summary>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.Customer.InStockNotificationSubscriptionCollection"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var instocknotificationsubscription = new InStockNotificationSubscription();
		///   var inStockNotificationSubscriptionCollection = instocknotificationsubscription.GetInStockNotificationSubscriptions();
		/// </code>
		/// </example>
		public virtual Mozu.Api.Contracts.Customer.InStockNotificationSubscriptionCollection GetInStockNotificationSubscriptions()
		{
			return GetInStockNotificationSubscriptions( null,  null,  null,  null, null);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="filter"></param>
		/// <param name="pageSize"></param>
		/// <param name="sortBy"></param>
		/// <param name="startIndex"></param>
		/// <param name="authTicket">User Auth Ticket{<see cref="Mozu.Api.Security.AuthTicket"/>}. If User Token is expired, authTicket will have a new Token and expiration date.</param>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.Customer.InStockNotificationSubscriptionCollection"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var instocknotificationsubscription = new InStockNotificationSubscription();
		///   var inStockNotificationSubscriptionCollection = instocknotificationsubscription.GetInStockNotificationSubscriptions( startIndex,  pageSize,  sortBy,  filter, authTicket);
		/// </code>
		/// </example>
		public virtual Mozu.Api.Contracts.Customer.InStockNotificationSubscriptionCollection GetInStockNotificationSubscriptions(int? startIndex =  null, int? pageSize =  null, string sortBy =  null, string filter =  null, AuthTicket authTicket= null)
		{
			MozuClient<Mozu.Api.Contracts.Customer.InStockNotificationSubscriptionCollection> response;
			var client = Mozu.Api.Clients.Commerce.InStockNotificationSubscriptionClient.GetInStockNotificationSubscriptionsClient( startIndex,  pageSize,  sortBy,  filter, authTicket);
			client.WithContext(_apiContext);
			response= client.Execute();
			return response.Result();

		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="id"></param>
		/// <param name="authTicket">User Auth Ticket{<see cref="Mozu.Api.Security.AuthTicket"/>}. If User Token is expired, authTicket will have a new Token and expiration date.</param>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.Customer.InStockNotificationSubscription"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var instocknotificationsubscription = new InStockNotificationSubscription();
		///   var inStockNotificationSubscription = instocknotificationsubscription.GetInStockNotificationSubscription( id, authTicket);
		/// </code>
		/// </example>
		public virtual Mozu.Api.Contracts.Customer.InStockNotificationSubscription GetInStockNotificationSubscription(int id, AuthTicket authTicket= null)
		{
			MozuClient<Mozu.Api.Contracts.Customer.InStockNotificationSubscription> response;
			var client = Mozu.Api.Clients.Commerce.InStockNotificationSubscriptionClient.GetInStockNotificationSubscriptionClient( id, authTicket);
			client.WithContext(_apiContext);
			response= client.Execute();
			return response.Result();

		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="authTicket">User Auth Ticket{<see cref="Mozu.Api.Security.AuthTicket"/>}. If User Token is expired, authTicket will have a new Token and expiration date.</param>
		/// <param name="inStockNotificationSubscription"></param>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.Customer.InStockNotificationSubscription"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var instocknotificationsubscription = new InStockNotificationSubscription();
		///   var inStockNotificationSubscription = instocknotificationsubscription.AddInStockNotificationSubscription( inStockNotificationSubscription, authTicket);
		/// </code>
		/// </example>
		public virtual Mozu.Api.Contracts.Customer.InStockNotificationSubscription AddInStockNotificationSubscription(Mozu.Api.Contracts.Customer.InStockNotificationSubscription inStockNotificationSubscription, AuthTicket authTicket= null)
		{
			MozuClient<Mozu.Api.Contracts.Customer.InStockNotificationSubscription> response;
			var client = Mozu.Api.Clients.Commerce.InStockNotificationSubscriptionClient.AddInStockNotificationSubscriptionClient( inStockNotificationSubscription, authTicket);
			client.WithContext(_apiContext);
			response= client.Execute();
			return response.Result();

		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="id"></param>
		/// <param name="authTicket">User Auth Ticket{<see cref="Mozu.Api.Security.AuthTicket"/>}. If User Token is expired, authTicket will have a new Token and expiration date.</param>
		/// <returns>
		/// 
		/// </returns>
		/// <example>
		/// <code>
		///   var instocknotificationsubscription = new InStockNotificationSubscription();
		///   instocknotificationsubscription.DeleteInStockNotificationSubscription( id, authTicket);
		/// </code>
		/// </example>
		public virtual void DeleteInStockNotificationSubscription(int id, AuthTicket authTicket= null)
		{
			MozuClient response;
			var client = Mozu.Api.Clients.Commerce.InStockNotificationSubscriptionClient.DeleteInStockNotificationSubscriptionClient( id, authTicket);
			client.WithContext(_apiContext);
			response= client.Execute();

		}


	}

}


