
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Mozu.Api.Security;


namespace Mozu.Api.Resources.Commerce.Catalog.Storefront
{
	/// <summary>
	/// 
	/// </summary>
	public partial class ProductSearchResultResource  	{
				///
		/// <see cref="Mozu.Api.ApiContext"/>
		///
		private readonly IApiContext _apiContext;
		public ProductSearchResultResource(IApiContext apiContext) 
		{
			_apiContext = apiContext;
		}

		
		/// <summary>
		/// 
		/// </summary>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.ProductRuntime.ProductSearchResult"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var productsearchresult = new ProductSearchResult();
		///   var productSearchResult = productsearchresult.Search();
		/// </code>
		/// </example>
		public virtual Mozu.Api.Contracts.ProductRuntime.ProductSearchResult Search()
		{
			return Search( null,  null,  null,  null,  null,  null,  null,  null,  null,  null,  null,  null,  null,  null,  null,  null, null);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="facet"></param>
		/// <param name="facetFieldRangeQuery"></param>
		/// <param name="facetHierDepth"></param>
		/// <param name="facetHierPrefix"></param>
		/// <param name="facetHierValue"></param>
		/// <param name="facetPageSize"></param>
		/// <param name="facetSettings"></param>
		/// <param name="facetStartIndex"></param>
		/// <param name="facetTemplate"></param>
		/// <param name="facetTemplateSubset"></param>
		/// <param name="facetValueFilter"></param>
		/// <param name="filter"></param>
		/// <param name="pageSize"></param>
		/// <param name="query"></param>
		/// <param name="sortBy"></param>
		/// <param name="startIndex"></param>
		/// <param name="authTicket">User Auth Ticket{<see cref="Mozu.Api.Security.AuthTicket"/>}. If User Token is expired, authTicket will have a new Token and expiration date.</param>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.ProductRuntime.ProductSearchResult"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var productsearchresult = new ProductSearchResult();
		///   var productSearchResult = productsearchresult.Search( facet,  facetFieldRangeQuery,  facetHierDepth,  facetHierPrefix,  facetHierValue,  facetPageSize,  facetSettings,  facetStartIndex,  facetTemplate,  facetTemplateSubset,  facetValueFilter,  filter,  pageSize,  query,  sortBy,  startIndex, authTicket);
		/// </code>
		/// </example>
		public virtual Mozu.Api.Contracts.ProductRuntime.ProductSearchResult Search(string facet =  null, string facetFieldRangeQuery =  null, string facetHierDepth =  null, string facetHierPrefix =  null, string facetHierValue =  null, string facetPageSize =  null, string facetSettings =  null, string facetStartIndex =  null, string facetTemplate =  null, string facetTemplateSubset =  null, string facetValueFilter =  null, string filter =  null, int? pageSize =  null, string query =  null, string sortBy =  null, int? startIndex =  null, AuthTicket authTicket= null)
		{
			MozuClient<Mozu.Api.Contracts.ProductRuntime.ProductSearchResult> response;
			var client = Mozu.Api.Clients.Commerce.Catalog.Storefront.ProductSearchResultClient.SearchClient( facet,  facetFieldRangeQuery,  facetHierDepth,  facetHierPrefix,  facetHierValue,  facetPageSize,  facetSettings,  facetStartIndex,  facetTemplate,  facetTemplateSubset,  facetValueFilter,  filter,  pageSize,  query,  sortBy,  startIndex, authTicket);
			client.WithContext(_apiContext);
			response= client.Execute();
			return response.Result();

		}

		/// <summary>
		/// 
		/// </summary>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.ProductRuntime.SearchSuggestion"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var productsearchresult = new ProductSearchResult();
		///   var searchSuggestion = productsearchresult.Suggest();
		/// </code>
		/// </example>
		public virtual Mozu.Api.Contracts.ProductRuntime.SearchSuggestion Suggest()
		{
			return Suggest( null,  null, null);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="pageSize"></param>
		/// <param name="q"></param>
		/// <param name="authTicket">User Auth Ticket{<see cref="Mozu.Api.Security.AuthTicket"/>}. If User Token is expired, authTicket will have a new Token and expiration date.</param>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.ProductRuntime.SearchSuggestion"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var productsearchresult = new ProductSearchResult();
		///   var searchSuggestion = productsearchresult.Suggest( pageSize,  q, authTicket);
		/// </code>
		/// </example>
		public virtual Mozu.Api.Contracts.ProductRuntime.SearchSuggestion Suggest(int? pageSize =  null, string q =  null, AuthTicket authTicket= null)
		{
			MozuClient<Mozu.Api.Contracts.ProductRuntime.SearchSuggestion> response;
			var client = Mozu.Api.Clients.Commerce.Catalog.Storefront.ProductSearchResultClient.SuggestClient( pageSize,  q, authTicket);
			client.WithContext(_apiContext);
			response= client.Execute();
			return response.Result();

		}

								
	}

}


