
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Mozu.Api.Urls.Commerce.Catalog.Admin
{
	public partial class ProductReservationUrl : MozuUrl
	{

		/// <summary>
        /// Get Resource Url for GetProductReservations
        /// </summary>
        /// <param name="filter"></param>
        /// <param name="pageSize"></param>
        /// <param name="sortBy"></param>
        /// <param name="startIndex"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetProductReservationsUrl(string filter, int? pageSize, string sortBy, int? startIndex)
		{
			var url = "/api/commerce/catalog/admin/productreservations/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}";
			FormatUrl( ref url, "filter", filter);
			FormatUrl( ref url, "pageSize", pageSize);
			FormatUrl( ref url, "sortBy", sortBy);
			FormatUrl( ref url, "startIndex", startIndex);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

		/// <summary>
        /// Get Resource Url for GetProductReservation
        /// </summary>
        /// <param name="productReservationId"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetProductReservationUrl(int productReservationId)
		{
			var url = "/api/commerce/catalog/admin/productreservations/{productReservationId}";
			FormatUrl( ref url, "productReservationId", productReservationId);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

				/// <summary>
        /// Get Resource Url for AddProductReservation
        /// </summary>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl AddProductReservationUrl()
		{
			var url = "/api/commerce/catalog/admin/productreservations/";
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

		/// <summary>
        /// Get Resource Url for CommitReservation
        /// </summary>
        /// <param name="productReservationId"></param>
        /// <param name="qty"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl CommitReservationUrl(int productReservationId, int qty)
		{
			var url = "/api/commerce/catalog/admin/productreservations/{productReservationId}/commit/{qty}";
			FormatUrl( ref url, "productReservationId", productReservationId);
			FormatUrl( ref url, "qty", qty);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

				/// <summary>
        /// Get Resource Url for UpdateProductReservation
        /// </summary>
        /// <param name="productReservationId">Unique identifier of the product reservation to update. </param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl UpdateProductReservationUrl(int productReservationId)
		{
			var url = "/api/commerce/catalog/admin/productreservations/{productReservationId}";
			FormatUrl( ref url, "productReservationId", productReservationId);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

				/// <summary>
        /// Get Resource Url for DeleteProductReservation
        /// </summary>
        /// <param name="productReservationId"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl DeleteProductReservationUrl(int productReservationId)
		{
			var url = "/api/commerce/catalog/admin/productreservations/{productReservationId}";
			FormatUrl( ref url, "productReservationId", productReservationId);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

		
	}
}

