
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Mozu.Api.Contracts.Core;

namespace Mozu.Api.Contracts.SiteSettings.Order
{
		///
		///	Settings that determine how orders are processed and order payments are authorized for the site.
		///
		public class OrderProcessingSettings
		{
			///
			///Determines whether payment authorization occurs when the order is placed or when the order is shipped.
			///
			public string PaymentProcessingFlowType { get; set; }

			///
			///If true, use the override price defined for products in the order to calculate discounts for the order.
			///
			public bool UseOverridePriceToCalculateDiscounts { get; set; }

			///
			///Identifier and datetime stamp information recorded when creating or updating a resource entity. System-supplied and read-only.
			///
			public AuditInfo AuditInfo { get; set; }

		}

}