
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Mozu.Api.Urls.Commerce.Orders
{
	public partial class OrderAttributeUrl : MozuUrl
	{

		/// <summary>
        /// Get Resource Url for GetOrderAttributes
        /// </summary>
        /// <param name="orderId">Identifier of the order whose order attributes are being retrieved.</param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl GetOrderAttributesUrl(string orderId)
		{
			var url = "/api/commerce/orders/{orderId}/attributes";
			FormatUrl( ref url, "orderId", orderId);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

				/// <summary>
        /// Get Resource Url for CreateOrderAttributes
        /// </summary>
        /// <param name="orderId">Identifier of the order whose attributes are being created.</param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl CreateOrderAttributesUrl(string orderId)
		{
			var url = "/api/commerce/orders/{orderId}/attributes";
			FormatUrl( ref url, "orderId", orderId);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

				/// <summary>
        /// Get Resource Url for UpdateOrderAttributes
        /// </summary>
        /// <param name="orderId">Identifier of the order whose order attributes are being updated.</param>
        /// <param name="removeMissing">If true, the operation removes missing properties so that the updated order attributes will not show properties with a null value.</param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl UpdateOrderAttributesUrl(string orderId, bool? removeMissing)
		{
			var url = "/api/commerce/orders/{orderId}/attributes?removeMissing={removeMissing}";
			FormatUrl( ref url, "orderId", orderId);
			FormatUrl( ref url, "removeMissing", removeMissing);
			return new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD) ;
		}

				
	}
}

